name: Super-Linter

# on: push
on:
  workflow_call: 
    inputs:
      Source_code:
        description: 'Full path to the project repo'
        required: true
        default: 'dummy.cpp'
        type: string
      job_id:
        description: 'id'
        required: true
        default: '1234'
        type: string
      runner_details:
        description: ' workflow runner'
        required: true
        type: string

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
